closes #2
segeda/svatky-api-nodejs pull request #3
Opened 2020-08-05 01:27 UTC by adybas

Hi, I went ahead and wrote out an English readme with documentation. I really liked this API and just want to make sure the documentation can reflect how awesome it is.

2020-08-05 05:07 UTC, segeda commented
@adybas Great work! 👍 
But maybe update original README.md with your english version and delete README.en-US.md. Every czech developer can read english documentation.
Thanks

2020-08-06 01:05 UTC, adybas commented
Okay, awesome! I'll go ahead and make those changes; I didn't want to assume that every Czech developer could read them, so that is good to know.

2020-08-06 06:44 UTC, segeda requested changes
some typos

2020-08-06 06:44 UTC, segeda commented on README.md
> +This API only accpets **GET** requests with three parameters: date, name, lang.
```suggestion
This API only accept **GET** requests with three parameters: date, name, lang.
```

2020-08-06 06:44 UTC, segeda commented on README.md
> +For example, if we wanted to seach for when the Name Day is of Anna in JSON, we would set the parameters up like so:
```suggestion
For example, if we wanted to search for when the Name Day is of Anna in JSON, we would set the parameters up like so:
```

2020-08-06 22:45 UTC, adybas reviewed
Thank you for catching the typos! Fixed them in update. 

Let me know if there is anything else you would like me to add or expand upon in the documentation.

2020-08-07 05:34 UTC, merged